# le nom du champ du formulaire (name) donc très important
<simpleSelect>      							
	type = select	
	width = 250

	# ce qui sera affiché devant le champ (moins important)
	display = Un Select Simple 

	# la valeur par défault					
	default_value = M. 							
	<options>
		type = constant

		# les valeurs possibles
		values = M./Mme/Mlle

		# ce qui est affiché pour chaque valeur (respecter l'ordre)					
		displays = Monsieur/Madame/Mademoiselle	
	</options>
</simpleSelect>

<multiSelect>
	type = select
	width = 250
	display = Un Select Multiple
	multi
	nb_lines = 5
	default_value = 0
	<options>
		type = constant
		values = 0/1/2/3/4
		displays = Noir/Bleu/Blanc/Rouge/Vert
	</options>
</multiSelect>

<anInput>
	type = input
	width = 300
	display = Un input simple requis
	maxlength = 10
	required
</anInput>

<anInput2>
	type = input
	width = 300
	display = Un input disabled
	disabled
</anInput2>

<aNumberInput>
	type = number
	width = 100
	step = 20
	min = 10
	max = 200
	display = Un input type number
</aNumberInput>

<multiline>
	type = input
	width = 300
	display = Ligne Texte Multiple
	multi
	required
	#disabled
</multiline>

<boxes>
	type = checkbox
	display = Checkboxes
	<options>
		type = constant
		values = 0/1/2/3/4
		displays = Noir/Bleu/Blanc/Rouge/Vert
	</options>
	required
</boxes>


<fieldset_1>
	hiddeable
	display = Un groupe de champs
	help = samples/resources/help_content_for_mform.txt  #une aide pour tout le fieldset
	<radioboxes>
		type = radio
		display = Radioboxes
		<options>
			type = constant
			values = 0/1/2/3/4
			displays = Noir/Bleu/Blanc/Rouge/Vert
		</options>
		required
	</radioboxes>
	
	<date1>
		type = date;
		display = Une Date
		format = d/m/Y
		min = 01/01/2015;
		max = 31/12/2019;
	</date1>
	<date2>
		type = date;
		display = Une autre
		format = d/m/Y
		min = Y;
		max = Y+4;
	</date2>
</fieldset_1>
	
<datetime>
		type = datetime
		display = Une date et une heure
		min = D;
		max = Y;
</datetime>
<anInput3>
	type = input
	width = 400
	display = Ligne Texte large avec Aide
	help = samples/resources/help_content_for_mform.txt
</anInput3>

<fichier>
	type = file
	width = 400
	display = Un Fichier
	help = samples/resources/help_content_for_mform.txt
	required
</fichier>

<aComplexSample>
	type = complex
	display = Info complémentaire
	help = samples/resources/help_content_for_mform.txt
	multi
	<info>      							
		type = select	
		width = 250
		display = Information						
		<options>
			type = constant
			values = tel/level/comment
			displays = Telephone/Niveau/Commentaire	
		</options>
		required
	</info>
	<required>
		type = radio
		display = Requis
		<options>
			type = constant
			values = 1/0
			displays = Oui/Non
		</options>
		required
	</required>
</aComplexSample>

<submit>
	display = Envoyer
	captcha = "samples/resources/captcha_for_mform.php"
</submit>
