# le nom du champ du formulaire (name) donc super important
<section1> # test d'un commentaire apres une balise ouvrante
	type = select; # test d'un commentaire apres unpaire cle-valeur finie
	width = 100  # test d'un commentaire apres unpaire cle-valeur non finie

	display = SelectSimple 
	default_value = une valeur avec un = dedans et un commentaire à la fin #le commentaire
	<options>
		type = "constant"

		# les valeurs possibles
		values = M./Mme/Mlle

		# ce qui est affiché pour chaque valeur (respecter l'ordre)					
		display = "Monsieur/Madame/Mademoiselle"
	</options>
	#required
	#disabled
</section1>

parametreBooleen
parametreBooleenFalse = false